# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-10 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_Table',
            new_name='UsersTable',
        ),
    ]
